<?php

declare(strict_types=1);

/*
 * This file is part of Augias project.
 *
 * (c) Pierre du Plessis <open-source@solidworx.co>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

// !! This file is autogenerated. Do not edit. !!

namespace Augias\NotificationBundle\Configurator;

use Augias\NotificationBundle\Form\Type\Transport\TelegramType;
use Symfony\Component\DependencyInjection\Attribute\AsTaggedItem;
use Symfony\Component\Notifier\Transport\Dsn;
use function explode;
use function rawurlencode;
use function sprintf;
use function trim;
use function urlencode;

/**
 * @codeCoverageIgnore
 */
#[AsTaggedItem('Telegram')]
final class TelegramConfigurator implements ConfiguratorInterface
{
    public static function getName(): string
    {
        return 'Telegram';
    }

    public static function getType(): string
    {
        return 'chatter';
    }

    public function getForm(): string
    {
        return TelegramType::class;
    }

    /**
     * @param array{ token: string, chat_id: string } $config
     */
    public function configure(array $config): Dsn
    {
        // A bot token is "<bot id>:<secret>", and Symfony reads it as the
        // user and password of the DSN: the colon has to stay one. Encoded
        // whole, it became %3A, and every real token was "Malformed token"
        // (test instance, 29/09/2026). Each half is encoded on its own.
        [$botId, $secret] = explode(':', trim($config['token']), 2) + [1 => ''];

        return new Dsn(sprintf('telegram://%s:%s@default?channel=%s', rawurlencode($botId), rawurlencode($secret), urlencode(trim($config['chat_id']))));
    }
}
